export const AstroData = [
  {
    id: 1,
    name: "Priya Sharma",
    designation: "Tarot Reader",
    rating: 4.9,
    number: "15K+ Orders",
    language: "Hindi, English",
    experience: "8 Years",
    price: 10,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 2,
    name: "Rahul Verma",
    designation: "Vedic Astrologer",
    rating: 4.8,
    number: "22K+ Orders",
    language: "English",
    experience: "12 Years",
    price: 15,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 3,
    name: "Anjali Gupta",
    designation: "Numerologist",
    rating: 4.7,
    number: "18K+ Orders",
    language: "Hindi",
    experience: "6 Years",
    price: 12,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 4,
    name: "Vikram Singh",
    designation: "Palm Reader",
    rating: 4.8,
    number: "20K+ Orders",
    language: "Hindi, English",
    experience: "10 Years",
    price: 14,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 5,
    name: "Sneha Kapoor",
    designation: "Tarot Reader",
    rating: 4.9,
    number: "25K+ Orders",
    language: "English",
    experience: "9 Years",
    price: 16,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 6,
    name: "Amit Joshi",
    designation: "Vedic Astrologer",
    rating: 4.6,
    number: "12K+ Orders",
    language: "Hindi",
    experience: "7 Years",
    price: 11,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 7,
    name: "Neha Mishra",
    designation: "Tarot Reader",
    rating: 4.8,
    number: "17K+ Orders",
    language: "Hindi, English",
    experience: "8 Years",
    price: 13,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 8,
    name: "Karan Malhotra",
    designation: "Palm Reader",
    rating: 4.7,
    number: "14K+ Orders",
    language: "English",
    experience: "5 Years",
    price: 10,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 9,
    name: "Riya Arora",
    designation: "Numerologist",
    rating: 4.9,
    number: "28K+ Orders",
    language: "Hindi, English",
    experience: "11 Years",
    price: 18,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 10,
    name: "Sanjay Mehta",
    designation: "Vedic Astrologer",
    rating: 4.8,
    number: "19K+ Orders",
    language: "Hindi",
    experience: "13 Years",
    price: 20,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 11,
    name: "Pooja Khanna",
    designation: "Tarot Reader",
    rating: 4.9,
    number: "16K+ Orders",
    language: "English",
    experience: "7 Years",
    price: 12,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 12,
    name: "Deepak Roy",
    designation: "Palm Reader",
    rating: 4.7,
    number: "13K+ Orders",
    language: "Hindi",
    experience: "6 Years",
    price: 9,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 13,
    name: "Meera Nair",
    designation: "Numerologist",
    rating: 4.8,
    number: "21K+ Orders",
    language: "English, Malayalam",
    experience: "10 Years",
    price: 15,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 14,
    name: "Rohit Sharma",
    designation: "Vedic Astrologer",
    rating: 4.9,
    number: "30K+ Orders",
    language: "Hindi, English",
    experience: "14 Years",
    price: 22,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 15,
    name: "Kavya Jain",
    designation: "Tarot Reader",
    rating: 4.8,
    number: "11K+ Orders",
    language: "Hindi",
    experience: "5 Years",
    price: 10,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 16,
    name: "Arjun Patel",
    designation: "Palm Reader",
    rating: 4.7,
    number: "18K+ Orders",
    language: "Gujarati, English",
    experience: "9 Years",
    price: 14,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 17,
    name: "Simran Kaur",
    designation: "Numerologist",
    rating: 4.9,
    number: "26K+ Orders",
    language: "Punjabi, English",
    experience: "12 Years",
    price: 17,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 18,
    name: "Manish Tiwari",
    designation: "Vedic Astrologer",
    rating: 4.6,
    number: "10K+ Orders",
    language: "Hindi",
    experience: "7 Years",
    price: 11,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 19,
    name: "Nidhi Agarwal",
    designation: "Tarot Reader",
    rating: 4.8,
    number: "19K+ Orders",
    language: "Hindi, English",
    experience: "8 Years",
    price: 13,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 20,
    name: "Yash Malhotra",
    designation: "Palm Reader",
    rating: 4.7,
    number: "15K+ Orders",
    language: "English",
    experience: "6 Years",
    price: 10,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 21,
    name: "Shreya Das",
    designation: "Numerologist",
    rating: 4.9,
    number: "27K+ Orders",
    language: "Hindi, Bengali",
    experience: "11 Years",
    price: 18,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 22,
    name: "Ajay Kulkarni",
    designation: "Vedic Astrologer",
    rating: 4.8,
    number: "24K+ Orders",
    language: "Marathi, English",
    experience: "13 Years",
    price: 20,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 23,
    name: "Ishita Sen",
    designation: "Tarot Reader",
    rating: 4.9,
    number: "14K+ Orders",
    language: "English",
    experience: "6 Years",
    price: 12,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 24,
    name: "Harsh Vardhan",
    designation: "Palm Reader",
    rating: 4.7,
    number: "16K+ Orders",
    language: "Hindi",
    experience: "8 Years",
    price: 13,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 25,
    name: "Tanvi Gupta",
    designation: "Numerologist",
    rating: 4.8,
    number: "20K+ Orders",
    language: "Hindi, English",
    experience: "10 Years",
    price: 15,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 26,
    name: "Suresh Reddy",
    designation: "Vedic Astrologer",
    rating: 4.9,
    number: "32K+ Orders",
    language: "Telugu, English",
    experience: "15 Years",
    price: 25,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 27,
    name: "Aisha Khan",
    designation: "Tarot Reader",
    rating: 4.8,
    number: "18K+ Orders",
    language: "Hindi, Urdu",
    experience: "7 Years",
    price: 12,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 28,
    name: "Nitin Bansal",
    designation: "Palm Reader",
    rating: 4.7,
    number: "13K+ Orders",
    language: "Hindi",
    experience: "5 Years",
    price: 9,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 29,
    name: "Ritika Malhotra",
    designation: "Numerologist",
    rating: 4.9,
    number: "23K+ Orders",
    language: "English, Hindi",
    experience: "12 Years",
    price: 17,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
  {
    id: 30,
    name: "Vivek Chaturvedi",
    designation: "Vedic Astrologer",
    rating: 4.8,
    number: "29K+ Orders",
    language: "Hindi, English",
    experience: "14 Years",
    price: 21,
    image:
      "https://ik.imagekit.io/ilvdampsx/servicesImages/S12.png?updatedAt=1781784837299",
  },
];
